import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';
// import Link from 'next/link';
// import Counter from '../components/Counter';
import Post from './blog/post';
import { Grid, Card, Text } from "@nextui-org/react";
import { useMediaQuery } from './useMediaQuery.js';
import Example from './Example';
import { env } from '../next.config';
// import { Add, Sub, Mul, Div } from '../components/Calculator';

// const data = {
//   'a' : 10,
//   'b' : 20
// }

// const data = [15, 25];

export default function Home() {
  // const user = process.env.DB_USER;
  // console.log(user);
  const isMd = useMediaQuery(960);

  const MockItem = ({ text }) => {
    return (
      <Card css={{ h: "$20", $$cardColor: '$colors$primary' }}>
        <Card.Body>
          <Text h6 size={15} color="white" css={{ m: 0 }}>
            {text}
          </Text>
        </Card.Body>
      </Card>
    );
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Grid.Container gap={2} justify="center">
          <Grid xs={12}>
            <Example />
          </Grid>

          <Grid xs={12}>
            <Grid xs={3}>
              <MockItem text="1 of 3" />
            </Grid>
            <Grid xs={6}>
              <Post />
            </Grid>
            <Grid xs={3}>
              <MockItem text="3 of 3" />
            </Grid>
          </Grid>

        </Grid.Container>

        {/* <button style={{ color: 'red' }}>
          <Link href='/blog'>
            <a>Blog</a>
          </Link>
        </button>
        <Counter /> */}
        {/* <Add data={data} />
        <Sub data={data} />
        <Mul data={data} />
        <Div data={data} /> */}
      </main>
    </div>
  )
}
